from setuptools import setup

APP = ["main.py"]
DATA_FILES = [
    ("assets", [
        "assets/icon.png",
        "assets/icon.icns",
        "assets/logo_1.png",
        "assets/logo_2.png",
        "assets/combo_arrow_dark.svg",
        "assets/combo_arrow_light.svg",
        "assets/spin_up_dark.svg",
        "assets/spin_up_light.svg",
        "assets/spin_down_dark.svg",
        "assets/spin_down_light.svg",
        "assets/connection.svg",
        "assets/device.svg",
        "assets/extras.svg",
        "assets/flash_sd.svg",
        "assets/mister_settings.svg",
        "assets/savemanager.svg",
        "assets/scripts.svg",
        "assets/wallpapers.svg",
        "assets/zapscripts.svg",
        "assets/companion_remote.sh",
    ]),
]

OPTIONS = {
    "iconfile": "assets/icon.icns",
    "argv_emulation": False,
    "plist": {
        "CFBundleName": "MiSTer Companion",
        "CFBundleDisplayName": "MiSTer Companion",
        "CFBundleIdentifier": "com.enfstudios.mistercompanion",
        "CFBundleVersion": "4.3.0",
        "CFBundleShortVersionString": "4.3.0",
        "NSHighResolutionCapable": True,
        "LSMinimumSystemVersion": "11.0",
        "NSRequiresAquaSystemAppearance": False,
        "NSHumanReadableCopyright": "Original by Anime0t4ku. macOS port by ENF Studios.",
    },
    "packages": [
        "PyQt6",
        "paramiko",
        "requests",
        "websocket",
        "psutil",
        "cryptography",
        "cffi",
        "nacl",
        "charset_normalizer",
        "idna",
        "urllib3",
        "certifi",
        "serial",
    ],
    "includes": [
        "_cffi_backend",
        "core",
        "core.app_info",
        "core.app_paths",
        "core.arcade_organizer_offline",
        "core.config",
        "core.connection",
        "core.connection_monitor",
        "core.device_actions",
        "core.device_profiles",
        "core.extras_3s_arm",
        "core.extras_actions",
        "core.extras_common",
        "core.extras_ra_cores",
        "core.extras_sonic_mania",
        "core.extras_zaparoo_launcher",
        "core.flasher",
        "core.manuals",
        "core.mister_ini",
        "core.nfc_reader",
        "core.nfc_writer",
        "core.open_helpers",
        "core.remote_daemon",
        "core.mister_settings_backup",
        "core.profile_folder_sync",
        "core.ra_image_cache",
        "core.retroaccount",
        "core.retroachievements_api",
        "core.savemanager",
        "core.scripts_actions",
        "core.scripts_auto_time",
        "core.scripts_cifs_mount",
        "core.scripts_common",
        "core.scripts_dav_browser",
        "core.scripts_ftp_save_sync",
        "core.scripts_migrate_sd",
        "core.scripts_ra_viewer",
        "core.scripts_static_wallpaper",
        "core.scripts_syncthing",
        "core.scripts_update_all",
        "core.scripts_zaparoo",
        "core.share_opener",
        "core.theme",
        "core.update_all_config",
        "core.update_all_offline",
        "core.updater",
        "core.wallpapers",
        "core.zaplauncher_db",
        "core.zapscripts",
        "ui",
        "ui.custom_dialog",
        "ui.custom_message_dialog",
        "ui.scaling",
    ],
    "excludes": [
        "tkinter",
        "test",
        "unittest",
        "pydoc",
    ],
}

setup(
    app=APP,
    name="MiSTer Companion",
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
